### Register
POST http://45.32.28.204:8081/api/auth/signup HTTP/1.1
content-type: application/json

{
  "username": "long",
  "email": "thanhlong25042001@gmail.com",
  "password": "1"
}

### confirm
GET http://localhost:8081/api/auth/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRoYW5obG9uZzI1MDQyMDAxQGdtYWlsLmNvbSIsImlhdCI6MTY4NTUwODA4NH0.TngYg74vxPIq4GY2MaEIOgAmyVkBzqF7l6A98DLn-bI HTTP/1.1
content-type: application/json

### forgot password
POST http://localhost:8081/api/auth/forgotpassword HTTP/1.1
content-type: application/json

{
  "username": "long"
}

### reset password
POST http://localhost:8081/api/auth/verify-forget-password HTTP/1.1
Content-Type: application/json

{
  "confirmationCode": "535920",
  "username": "long"
}
### password reset
POST http://localhost:8081/api/auth/password-reset HTTP/1.1
Content-Type: application/json

{
  "_id":"64939fa184be3e5eebb368f9",
  "newPassword": "2"
}

### sign in
POST http://45.32.28.204:8081/api/auth/signin HTTP/1.1
Content-Type: application/json

{
  "username": "doctor2",
  "password": "1"
}

### change password
POST http://45.32.28.204:8081/api/auth/change-password HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJzdGF0dXMiOiJBY3RpdmUiLCJyb2xlcyI6InVzZXIiLCJfaWQiOiI2NDkzOWZhMTg0YmUzZTVlZWJiMzY4ZjkiLCJ1c2VybmFtZSI6ImxvbmciLCJlbWFpbCI6InRoYW5obG9uZzI1MDQyMDAxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA4JFNNU3U4TzZkQ05uMFJDVFIucHE3MWV3d040OXNYeDdYZG9LVXNHbFNTenlvLk02c1pZOVdlIiwiY29uZmlybWF0aW9uQ29kZSI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpsYldGcGJDSTZJblJvWVc1b2JHOXVaekkxTURReU1EQXhRR2R0WVdsc0xtTnZiU0lzSW1saGRDSTZNVFk0TnpNNU5qSTFOMzAuMjh0ZnY5T0QyeW1UMUl5dXZWS3hGLXBSWm1MSjBjeVVyR1VnZ0FTYlJsSSIsIl9fdiI6MH0sImlhdCI6MTY4Nzc0NzQ1OSwiZXhwIjoxNjg3ODMzODU5fQ.oPJfnyHGsTC6JRowoV8quu1CzJvptIqVaZO3IzJpOAQ

{
  "password":"1",
  "newPassword": "2"
}
