### get all medical record of patient
POST http://45.32.28.204:8081/api/patient/get-medical-record HTTP/1.1
Content-Type: application/json

{
  "patientId": "6493a3a563561b691315b459"
}

### get schedule speciality
// done
POST http://45.32.28.204:8081/api/patient/get-schedule-speciality HTTP/1.1
Content-Type: application/json

{
  "specialityID": "64532f139ec3cad23c35c886",
  "appointmentDate": "2021-05-01"
}

### get schedule doctor
//done
POST http://45.32.28.204:8081/api/patient/get-schedule-doctor HTTP/1.1
Content-Type: application/json

{
  "doctorID": "647f0fa156926b0f05f07f74",
  "appointmentDate": "2021-05-01"
}

### create appointment schedule by speciality
POST http://45.32.28.204:8081/api/patient/create-appointment-schedule-speciality HTTP/1.1
Content-Type: application/json

{
  "appointmentDate": "22-05-2021",
  "appointmentTime": "10:00",
  "specialityID": "647ee9e5aee1ff0c2b4ded1a",
  "patientID": "64532f139ec3cad23c35c886",
  "status": "booked",
  "description": "description"
}

### create appointment schedule doctor
//done 90% check error
POST http://45.32.28.204:8081/api/schedule/create-schedule-doctor HTTP/1.1
Content-Type: application/json

{
  "appointmentDate": "2021-05-01",
  "appointmentTime": "10:00",
  "specialityID": "647ee9e5aee1ff0c2b4ded18",
  "patientID": "64532f139ec3cad23c35c886",
  "status": "booked",
  "description": "description",
  "doctorID": "64532f139ec3cad23c35c889"
}

### create appointment schedule doctor
//done 90% check error
POST http://45.32.28.204:8081/api/patient/create-schedule HTTP/1.1
Content-Type: application/json

{
  "appointmentDate": "22-05-2021",
  "appointmentTime": "10:00",
  "specialityID": "647ee9e5aee1ff0c2b4ded18",
  "patientID": "64532f139ec3cad23c35c886",
  "status": "booked",
  "description": "description",
  "doctorID": "647f0f9c56926b0f05f07ed0"
}



### update data patient
POST http://45.32.28.204:8081/api/patient/update-patient HTTP/1.1
Content-Type: application/json

{
  "name" : "Lương Thanh Long",
  "dateOfBirth" : "25-04-2001",
  "phone": "012345678",
  "address": "Quảng Nam",
  "userId": "64939fa184be3e5eebb368f9"
}
